In [15]:
import pandas as pd
selloutData=pd.read_csv("./dataset/kopo_channel_seasonality_new.csv")

In [16]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine 
import pymysql
# import d6tstack

In [13]:
engine = create_engine('postgresql://postgres:postgres@192.168.110.111:5432/kopo')

In [4]:
selloutData.columns=selloutData.columns.str.lower()

In [5]:
resultname='pgresult'
selloutData.to_sql(name ="pgout",con = engine, index = False ,if_exists = "replace")

In [6]:
##mysql performance tip
# 옆에 있는 동료의 postgreSQL 서버에 접속 한후
# “kopo_product_volume” 자료를 불러와서
# 컬럼명을 변경 후 자신의 postgreSQL에 저장하세요

In [7]:
engine = create_engine('mysql+pymysql://sybabo:sybabo@192.168.110.3:3306/test')
engine2 = create_engine('postgresql://postgres:postgres@192.168.110.111:5432/kopo')

In [14]:
selloutData=pd.read_sql_query('SELECT*FROM sun_young_babo',engine)

ProgrammingError: (psycopg2.ProgrammingError) relation "sun_young_babo" does not exist
LINE 1: SELECT*FROM sun_young_babo
                    ^
 [SQL: 'SELECT*FROM sun_young_babo'] (Background on this error at: http://sqlalche.me/e/f405)

In [17]:
selloutData.head()

  REGIONID    PRODUCT  YEARWEEK      QTY
0      A60   PRODUCT4    201402     71.0
1      A60  PRODUCT59    201402  22275.0
2      A60  PRODUCT34    201402   4463.0
3      A60  PRODUCT47    201402      0.0
4      A60  PRODUCT56    201402     23.0

In [18]:
selloutData.to_sql(name ="pgtest222222222",con = engine2, index = False ,if_exists = "replace")

In [19]:
selloutData=pd.read_csv("./dataset/kopo_channel_seasonality_new.csv")
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
dtype: object

In [20]:
### 1.타입전환

In [21]:
selloutData["YEARWEEK"] = selloutData.YEARWEEK.astype("str")
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK     object
QTY         float64
dtype: object

In [22]:
selloutData.min()

REGIONID         A00
PRODUCT     PRODUCT1
YEARWEEK      201401
QTY             -364
dtype: object

In [23]:
####2.행열 조회

In [24]:
len(selloutData[selloutData.QTY<0])

323

In [25]:
selloutData2=selloutData[selloutData.QTY<0]

In [26]:
###3.데이터 정제

In [27]:
import numpy as np

In [28]:
selloutData["NEW_QTY"]=np.where(selloutData.QTY<0,0,selloutData.QTY)

In [29]:
selloutData[selloutData.QTY>=0][selloutData.QTY == selloutData.NEW_QTY]

C:\Users\SMART-14\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

       REGIONID    PRODUCT YEARWEEK       QTY   NEW_QTY
0           A60   PRODUCT4   201402      71.0      71.0
1           A60  PRODUCT59   201402   22275.0   22275.0
2           A60  PRODUCT34   201402    4463.0    4463.0
3           A60  PRODUCT47   201402       0.0       0.0
4           A60  PRODUCT56   201402      23.0      23.0
5           A60  PRODUCT57   201402      14.0      14.0
6           A60  PRODUCT12   201402    1186.0    1186.0
7           A60   PRODUCT1   201402       7.0       7.0
8           A60  PRODUCT33   201402     101.0     101.0
9           A60  PRODUCT62   201402     336.0     336.0
10          A37  PRODUCT58   201402       0.0       0.0
11          A37  PRODUCT59   201402   11492.0   11492.0
12          A37  PRODUCT34   201402     825.0     825.0
13          A31  PRODUCT58   201402       0.0       0.0
14          A31  PRODUCT59   201402     560.0     560.0
15          A31  PRODUCT34   201402     103.0     103.0
16          A04  PRODUCT58   201402       0.0       0.0
17          A04  PRODUCT63   201402     740.0     740.0
18          A04  PRODUCT15   201402     394.0     394.0
19          A04   PRODUCT4   201402    2550.0    2550.0
20          A04  PRODUCT16   201402       4.0       4.0
21          A04  PRODUCT59   201402   36549.0   36549.0
22          A04  PRODUCT34   201402    4773.0    4773.0
23          A04  PRODUCT40   201402     146.0     146.0
24          A04  PRODUCT47   201402       5.0       5.0
25          A04  PRODUCT60   201402       9.0       9.0
26          A04  PRODUCT56   201402     109.0     109.0
27          A04  PRODUCT57   201402    1195.0    1195.0
28          A04  PRODUCT12   201402   15028.0   15028.0
29          A04   PRODUCT1   201402    1319.0    1319.0
...         ...        ...      ...       ...       ...
124628      A16  PRODUCT64   201630     188.0     188.0
124629      A16  PRODUCT48   201630      16.0      16.0
124630      A16  PRODUCT49   201630       9.0       9.0
124631      A16  PRODUCT74   201630      18.0      18.0
124632      A16  PRODUCT40   201630     285.0     285.0
124633      A16  PRODUCT47   201630     155.0     155.0
124634      A16  PRODUCT60   201630    2491.0    2491.0
124635      A16  PRODUCT56   201630    2026.0    2026.0
124636      A16  PRODUCT12   201630   17067.0   17067.0
124637      A16   PRODUCT1   201630     168.0     168.0
124638      A16  PRODUCT41   201630       0.0       0.0
124639      A16  PRODUCT51   201630       0.0       0.0
124640      A16  PRODUCT68   201630       0.0       0.0
124641      A16  PRODUCT33   201630    3887.0    3887.0
124642      A16  PRODUCT14   201630      95.0      95.0
124643      A10   PRODUCT2   201630   12570.0   12570.0
124644      A10  PRODUCT58   201630    4461.0    4461.0
124645      A10  PRODUCT63   201630    4308.0    4308.0
124646      A10  PRODUCT15   201630       0.0       0.0
124647      A10   PRODUCT4   201630    3012.0    3012.0
124648      A10  PRODUCT16   201630     231.0     231.0
124649      A10  PRODUCT59   201630  231024.0  231024.0
124650      A10  PRODUCT34   201630   34436.0   34436.0
124651      A10  PRODUCT40   201630       0.0       0.0
124652      A10  PRODUCT47   201630       4.0       4.0
124653      A10  PRODUCT60   201630     824.0     824.0
124654      A10  PRODUCT56   201630     275.0     275.0
124655      A10  PRODUCT61   201630       0.0       0.0
124656      A10  PRODUCT12   201630   15021.0   15021.0
124657      A10   PRODUCT1   201630     568.0     568.0

[124335 rows x 5 columns]

In [30]:
selloutData["YEAR"]=selloutData.YEARWEEK.str[0:4]
selloutData["WEEK"]=selloutData.YEARWEEK.str[4:6]

In [31]:
selloutData.min()

REGIONID         A00
PRODUCT     PRODUCT1
YEARWEEK      201401
QTY             -364
NEW_QTY            0
YEAR            2014
WEEK              01
dtype: object

In [32]:
selloutData.max()

REGIONID            A77
PRODUCT        PRODUCT8
YEARWEEK         201652
QTY         1.66321e+06
NEW_QTY     1.66321e+06
YEAR               2016
WEEK                 53
dtype: object

In [33]:
refinedSelloutData = selloutData[selloutData.WEEK.astype(int) <= 52]

In [34]:
refinedSelloutData.max()

REGIONID            A77
PRODUCT        PRODUCT8
YEARWEEK         201652
QTY         1.66321e+06
NEW_QTY     1.66321e+06
YEAR               2016
WEEK                 52
dtype: object

In [35]:
### 데이터 정렬

In [36]:
sortKey=["REGIONID","PRODUCT","YEARWEEK"]

In [37]:
sortedData =refinedSelloutData.sort_values(sortKey)

In [38]:
groupKey=["REGIONID","PRODUCT"]
gfunction=["mean","std"]
groupData=sortedData.groupby(groupKey)["NEW_QTY"].agg(gfunction).reset_index()

In [39]:
groupData.rename(columns={"mean":"MEAN","std":"STD"},inplace=True)      ##inplace 중요!!

In [40]:
groupData.head()

  REGIONID    PRODUCT           MEAN            STD
0      A00  PRODUCT34     133.057692     155.176039
1      A00  PRODUCT58     105.250000     274.315679
2      A00  PRODUCT59   35957.570513   15154.625012
3      A01   PRODUCT1    5712.775641    3716.549078
4      A01  PRODUCT12  196825.403846  199486.717203

In [41]:
refinedSelloutData.columns

Index(['REGIONID', 'PRODUCT', 'YEARWEEK', 'QTY', 'NEW_QTY', 'YEAR', 'WEEK'], dtype='object')

In [42]:
groupData.columns

Index(['REGIONID', 'PRODUCT', 'MEAN', 'STD'], dtype='object')

In [43]:
joinKey = ["REGIONID","PRODUCT"]

In [44]:
joindata=pd.merge(refinedSelloutData,groupData,on =joinKey, how ="left")

In [45]:
reqcolumns = ["REGIONID","PRODUCT","YEARWEEK","YEAR","WEEK","NEW_QTY","MEAN"]

In [46]:
middleResult=joindata[reqcolumns]

In [47]:
middleResult["SEASONALITY"]=np.where(middleResult.MEAN !=0, middleResult.NEW_QTY/middleResult.MEAN,0)

C:\Users\SMART-14\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [48]:
finalgroupKey=["REGIONID","PRODUCT","WEEK"]
finalResult = middleResult.groupby(finalgroupKey)["SEASONALITY"].agg(["mean"]).reset_index()

In [49]:
finalResult.rename(columns={"mean":"SEASONALITY"},inplace =True)
seasonMap = finalResult.groupby(finalgroupKey)["SEASONALITY"].agg("mean").to_dict()

In [50]:
seasonMap

{('A00', 'PRODUCT34', '01'): 2.0868140868140865,
 ('A00', 'PRODUCT34', '02'): 2.234619646384352,
 ('A00', 'PRODUCT34', '03'): 1.7736667148431853,
 ('A00', 'PRODUCT34', '04'): 1.7886977886977886,
 ('A00', 'PRODUCT34', '05'): 1.5131281013633953,
 ('A00', 'PRODUCT34', '06'): 1.2876619935443463,
 ('A00', 'PRODUCT34', '07'): 1.2300428771017005,
 ('A00', 'PRODUCT34', '08'): 1.0772269595799007,
 ('A00', 'PRODUCT34', '09'): 1.305198246374717,
 ('A00', 'PRODUCT34', '10'): 1.5732523967818082,
 ('A00', 'PRODUCT34', '11'): 1.1849496555378907,
 ('A00', 'PRODUCT34', '12'): 1.0396492749433925,
 ('A00', 'PRODUCT34', '13'): 0.9820301585007467,
 ('A00', 'PRODUCT34', '14'): 0.9795249795249794,
 ('A00', 'PRODUCT34', '15'): 0.8367297779062484,
 ('A00', 'PRODUCT34', '16'): 0.8166883461001105,
 ('A00', 'PRODUCT34', '17'): 0.7265019029724913,
 ('A00', 'PRODUCT34', '18'): 0.5686756274991568,
 ('A00', 'PRODUCT34', '19'): 0.5160668690080453,
 ('A00', 'PRODUCT34', '20'): 0.5260875849111143,
 ('A00', 'PRODUCT34', '21'): 0.5210772269595799,
 ('A00', 'PRODUCT34', '22'): 0.5160668690080454,
 ('A00', 'PRODUCT34', '23'): 0.4384063207592619,
 ('A00', 'PRODUCT34', '24'): 0.39832345714698647,
 ('A00', 'PRODUCT34', '25'): 0.28308522426169486,
 ('A00', 'PRODUCT34', '26'): 0.2505178975767211,
 ('A00', 'PRODUCT34', '27'): 0.30813701401936694,
 ('A00', 'PRODUCT34', '28'): 0.4935202582261405,
 ('A00', 'PRODUCT34', '29'): 1.79621332562509,
 ('A00', 'PRODUCT34', '30'): 1.4079105843811723,
 ('A00', 'PRODUCT34', '31'): 1.2225273401743988,
 ('A00', 'PRODUCT34', '32'): 1.36532254179313,
 ('A00', 'PRODUCT34', '33'): 1.1097942862648744,
 ('A00', 'PRODUCT34', '34'): 1.1348460760225463,
 ('A00', 'PRODUCT34', '35'): 1.0972683913860384,
 ('A00', 'PRODUCT34', '36'): 1.0847424965072023,
 ('A00', 'PRODUCT34', '37'): 1.057185527773763,
 ('A00', 'PRODUCT34', '38'): 1.247579129932071,
 ('A00', 'PRODUCT34', '39'): 2.1694849930144042,
 ('A00', 'PRODUCT34', '40'): 0.7741003035120682,
 ('A00', 'PRODUCT34', '41'): 0.8843281784458253,
 ('A00', 'PRODUCT34', '42'): 0.8342245989304812,
 ('A00', 'PRODUCT34', '43'): 0.796646914293973,
 ('A00', 'PRODUCT34', '44'): 0.6287999229175698,
 ('A00', 'PRODUCT34', '45'): 0.7365226188755599,
 ('A00', 'PRODUCT34', '46'): 0.6939345762875174,
 ('A00', 'PRODUCT34', '47'): 0.7841210194151369,
 ('A00', 'PRODUCT34', '48'): 0.5486341956930191,
 ('A00', 'PRODUCT34', '49'): 0.4584477525653996,
 ('A00', 'PRODUCT34', '50'): 0.7490485137543961,
 ('A00', 'PRODUCT34', '51'): 0.6012429541841307,
 ('A00', 'PRODUCT34', '52'): 1.5607265019029724,
 ('A00', 'PRODUCT58', '01'): 0.2185273159144893,
 ('A00', 'PRODUCT58', '02'): 0.20902612826603326,
 ('A00', 'PRODUCT58', '03'): 0.11718131433095803,
 ('A00', 'PRODUCT58', '04'): 0.16152019002375298,
 ('A00', 'PRODUCT58', '05'): 0.14251781472684086,
 ('A00', 'PRODUCT58', '06'): 0.20269200316706257,
 ('A00', 'PRODUCT58', '07'): 0.28820269200316706,
 ('A00', 'PRODUCT58', '08'): 0.1583531274742676,
 ('A00', 'PRODUCT58', '09'): 0.1456848772763262,
 ('A00', 'PRODUCT58', '10'): 0.14251781472684086,
 ('A00', 'PRODUCT58', '11'): 0.11084718923198733,
 ('A00', 'PRODUCT58', '12'): 0.1520190023752969,
 ('A00', 'PRODUCT58', '13'): 0.06334125098970704,
 ('A00', 'PRODUCT58', '14'): 0.06334125098970705,
 ('A00', 'PRODUCT58', '15'): 0.06334125098970704,
 ('A00', 'PRODUCT58', '16'): 1.8020585906571656,
 ('A00', 'PRODUCT58', '17'): 1.1749802058590657,
 ('A00', 'PRODUCT58', '18'): 2.9897070467141726,
 ('A00', 'PRODUCT58', '19'): 3.2620744259699133,
 ('A00', 'PRODUCT58', '20'): 2.2169437846397466,
 ('A00', 'PRODUCT58', '21'): 1.5486935866983371,
 ('A00', 'PRODUCT58', '22'): 2.099762470308789,
 ('A00', 'PRODUCT58', '23'): 7.968329374505146,
 ('A00', 'PRODUCT58', '24'): 2.014251781472684,
 ('A00', 'PRODUCT58', '25'): 2.3372921615201903,
 ('A00', 'PRODUCT58', '26'): 2.6539984164687254,
 ('A00', 'PRODUCT58', '27'): 1.8083927157561364,
 ('A00', 'PRODUCT58', '28'): 1.950910530482977,
 ('A00', 'PRODUCT58', '29'): 1.707046714172605,
 ('A00', 'PRODUCT58', '30'): 1.4251781472684086,
 ('A00', 'PRODUCT58', '31'): 1.1559778305621535,
 ('A00', 'PRODUCT58', '32'): 1.0641330166270784,
 ('A00', 'PRODUCT58', '33'): 1.1749802058590657,
 ('A00', 'PRODUCT58', '34'): 0.8234362628661916,
 ('A00', 'PRODUCT58', '35'): 0.7569279493269992,
 ('A00', 'PRODUCT58', '36'): 0.7569279493269992,
 ('A00', 'PRODUCT58', '37'): 0.4813935075217735,
 ('A00', 'PRODUCT58', '38'): 0.601741884402217,
 ('A00', 'PRODUCT58', '39'): 0.5162311955661124,
 ('A00', 'PRODUCT58', '40'): 0.47189231987331753,
 ('A00', 'PRODUCT58', '41'): 0.4180522565320665,
 ('A00', 'PRODUCT58', '42'): 0.4655581947743468,
 ('A00', 'PRODUCT58', '43'): 0.5003958828186857,
 ('A00', 'PRODUCT58', '44'): 0.6872525732383216,
 ('A00', 'PRODUCT58', '45'): 0.4180522565320665,
 ('A00', 'PRODUCT58', '46'): 0.32937450514647665,
 ('A00', 'PRODUCT58', '47'): 0.45605700712589076,
 ('A00', 'PRODUCT58', '48'): 0.5700712589073634,
 ('A00', 'PRODUCT58', '49'): 0.5415676959619953,
 ('A00', 'PRODUCT58', '50'): 0.3610451306413302,
 ('A00', 'PRODUCT58', '51'): 0.09817893903404594,
 ('A00', 'PRODUCT58', '52'): 0.1520190023752969,
 ('A00', 'PRODUCT59', '01'): 1.0294725924304302,
 ('A00', 'PRODUCT59', '02'): 0.9716729885169147,
 ('A00', 'PRODUCT59', '03'): 0.943361843312123,
 ('A00', 'PRODUCT59', '04'): 0.9249976066877966,
 ('A00', 'PRODUCT59', '05'): 0.9741110471904119,
 ('A00', 'PRODUCT59', '06'): 1.0009667733391616,
 ('A00', 'PRODUCT59', '07'): 0.9751956588436407,
 ('A00', 'PRODUCT59', '08'): 0.884125360712706,
 ('A00', 'PRODUCT59', '09'): 0.825333846996665,
 ('A00', 'PRODUCT59', '10'): 0.8608850067413855,
 ('A00', 'PRODUCT59', '11'): 0.8629986089374211,
 ('A00', 'PRODUCT59', '12'): 0.8849782177391766,
 ('A00', 'PRODUCT59', '13'): 0.9723960629524004,
 ('A00', 'PRODUCT59', '14'): 0.9538371524415973,
 ('A00', 'PRODUCT59', '15'): 1.0418668298694633,
 ('A00', 'PRODUCT59', '16'): 0.87444728749928,
 ('A00', 'PRODUCT59', '17'): 0.7602942285432207,
 ('A00', 'PRODUCT59', '18'): 0.7773420988875599,
 ('A00', 'PRODUCT59', '19'): 0.8308681474836527,
 ('A00', 'PRODUCT59', '20'): 0.7899217400279994,
 ('A00', 'PRODUCT59', '21'): 0.7839239302874951,
 ('A00', 'PRODUCT59', '22'): 0.8383306464652694,
 ('A00', 'PRODUCT59', '23'): 0.8397582549661005,
 ('A00', 'PRODUCT59', '24'): 0.9438438929357801,
 ('A00', 'PRODUCT59', '25'): 0.9156161793966214,
 ('A00', 'PRODUCT59', '26'): 1.005231058471514,
 ('A00', 'PRODUCT59', '27'): 1.0010502050047947,
 ('A00', 'PRODUCT59', '28'): 1.0236879969465436,
 ('A00', 'PRODUCT59', '29'): 1.0847970569301675,
 ('A00', 'PRODUCT59', '30'): 1.0607131161174468,
 ('A00', 'PRODUCT59', '31'): 1.0572831476414242,
 ('A00', 'PRODUCT59', '32'): 1.1262904053049703,
 ('A00', 'PRODUCT59', '33'): 1.1108462769777985,
 ('A00', 'PRODUCT59', '34'): 1.0763704587012362,
 ('A00', 'PRODUCT59', '35'): 1.099054601568337,
 ('A00', 'PRODUCT59', '36'): 1.1473986167101147,
 ('A00', 'PRODUCT59', '37'): 1.0827854267699057,
 ('A00', 'PRODUCT59', '38'): 1.120709753892631,
 ('A00', 'PRODUCT59', '39'): 1.164835834827408,
 ('A00', 'PRODUCT59', '40'): 1.2145981882849461,
 ('A00', 'PRODUCT59', '41'): 1.0864193393174755,
 ('A00', 'PRODUCT59', '42'): 1.1133399567617175,
 ('A00', 'PRODUCT59', '43'): 0.9922527993730501,
 ('A00', 'PRODUCT59', '44'): 1.035841209573748,
 ('A00', 'PRODUCT59', '45'): 1.0835363117606025,
 ('A00', 'PRODUCT59', '46'): 1.08346215028004,
 ('A00', 'PRODUCT59', '47'): 1.0567362067222745,
 ('A00', 'PRODUCT59', '48'): 0.984271170027495,
 ('A00', 'PRODUCT59', '49'): 1.0930011707174108,
 ('A00', 'PRODUCT59', '50'): 1.1406221114237025,
 ('A00', 'PRODUCT59', '51'): 1.2251198483397723,
 ('A00', 'PRODUCT59', '52'): 1.2691995783491976,
 ('A01', 'PRODUCT1', '01'): 1.8511725294072103,
 ('A01', 'PRODUCT1', '02'): 1.2963925883618925,
 ('A01', 'PRODUCT1', '03'): 2.0165912434231417,
 ('A01', 'PRODUCT1', '04'): 1.4541676157689751,
 ('A01', 'PRODUCT1', '05'): 1.5231358415068341,
 ('A01', 'PRODUCT1', '06'): 1.3217742958034904,
 ('A01', 'PRODUCT1', '07'): 1.2114951531262028,
 ('A01', 'PRODUCT1', '08'): 1.2400276932157233,
 ('A01', 'PRODUCT1', '09'): 1.1785864565812345,
 ('A01', 'PRODUCT1', '10'): 1.008208098582462,
 ('A01', 'PRODUCT1', '11'): 0.9378395027788593,
 ('A01', 'PRODUCT1', '12'): 0.8848588352915701,
 ('A01', 'PRODUCT1', '13'): 0.894252984482598,
 ('A01', 'PRODUCT1', '14'): 0.7954101973422144,
 ('A01', 'PRODUCT1', '15'): 0.810814268065391,
 ('A01', 'PRODUCT1', '16'): 0.7641352658739465,
 ('A01', 'PRODUCT1', '17'): 0.7658273797033863,
 ('A01', 'PRODUCT1', '18'): 0.7152390110784085,
 ('A01', 'PRODUCT1', '19'): 0.6521056606144797,
 ('A01', 'PRODUCT1', '20'): 0.7515319352822565,
 ('A01', 'PRODUCT1', '21'): 0.7321018006200677,
 ('A01', 'PRODUCT1', '22'): 0.8150737270153604,
 ('A01', 'PRODUCT1', '23'): 0.7692116073622661,
 ('A01', 'PRODUCT1', '24'): 0.8541090425979557,
 ('A01', 'PRODUCT1', '25'): 0.8106392218071732,
 ('A01', 'PRODUCT1', '26'): 1.0321894359583166,
 ('A01', 'PRODUCT1', '27'): 0.9177675318365383,
 ('A01', 'PRODUCT1', '28'): 0.8916272906093293,
 ('A01', 'PRODUCT1', '29'): 0.9202765282043285,
 ('A01', 'PRODUCT1', '30'): 0.7639018708629894,
 ('A01', 'PRODUCT1', '31'): 0.8546341813726096,
 ('A01', 'PRODUCT1', '32'): 0.7748714363779787,
 ('A01', 'PRODUCT1', '33'): 0.8626863092506337,
 ('A01', 'PRODUCT1', '34'): 0.723582882720129,
 ('A01', 'PRODUCT1', '35'): 0.9788586759545913,
 ('A01', 'PRODUCT1', '36'): 0.7604592944513704,
 ('A01', 'PRODUCT1', '37'): 0.7912090871449844,
 ('A01', 'PRODUCT1', '38'): 0.8371295555508178,
 ('A01', 'PRODUCT1', '39'): 0.691666114971729,
 ('A01', 'PRODUCT1', '40'): 0.7318100568563713,
 ('A01', 'PRODUCT1', '41'): 0.6827971045553545,
 ('A01', 'PRODUCT1', '42'): 0.6468542728679422,
 ('A01', 'PRODUCT1', '43'): 0.7471557788268086,
 ('A01', 'PRODUCT1', '44'): 0.6486630842028607,
 ('A01', 'PRODUCT1', '45'): 0.8645534693382916,
 ('A01', 'PRODUCT1', '46'): 0.8537006013287806,
 ('A01', 'PRODUCT1', '47'): 1.1485368489204921,
 ('A01', 'PRODUCT1', '48'): 2.0629201530981507,
 ('A01', 'PRODUCT1', '49'): 1.5243028165616204,
 ('A01', 'PRODUCT1', '50'): 1.2923665244228804,
 ('A01', 'PRODUCT1', '51'): 1.491452468769391,
 ('A01', 'PRODUCT1', '52'): 1.4493246692916129,
 ('A01', 'PRODUCT12', '01'): 0.7758043271657886,
 ('A01', 'PRODUCT12', '02'): 0.6270091711829856,
 ('A01', 'PRODUCT12', '03'): 0.6550441701829778,
 ('A01', 'PRODUCT12', '04'): 0.8024506165378967,
 ('A01', 'PRODUCT12', '05'): 0.9815094811186134,
 ('A01', 'PRODUCT12', '06'): 0.7389882800919193,
 ('A01', 'PRODUCT12', '07'): 0.788251907366945,
 ('A01', 'PRODUCT12', '08'): 0.760746988993206,
 ('A01', 'PRODUCT12', '09'): 0.7516797312521187,
 ('A01', 'PRODUCT12', '10'): 0.7476338442996613,
 ('A01', 'PRODUCT12', '11'): 0.7264627966677352,
 ('A01', 'PRODUCT12', '12'): 0.7030071523431071,
 ('A01', 'PRODUCT12', '13'): 0.6809503789363234,
 ('A01', 'PRODUCT12', '14'): 0.6777292500189628,
 ('A01', 'PRODUCT12', '15'): 0.6380426385313575,
 ('A01', 'PRODUCT12', '16'): 0.6422307835432569,
 ('A01', 'PRODUCT12', '17'): 0.6360273160225988,
 ('A01', 'PRODUCT12', '18'): 0.6994337653737955,
 ('A01', 'PRODUCT12', '19'): 0.6718865082918893,
 ('A01', 'PRODUCT12', '20'): 0.6793279596393562,
 ('A01', 'PRODUCT12', '21'): 0.7736450530492615,
 ('A01', 'PRODUCT12', '22'): 0.8241754544726497,
 ('A01', 'PRODUCT12', '23'): 0.6790061854572856,
 ('A01', 'PRODUCT12', '24'): 0.7497473926113679,
 ('A01', 'PRODUCT12', '25'): 0.6881665883563407,
 ('A01', 'PRODUCT12', '26'): 0.7755655368517256,
 ('A01', 'PRODUCT12', '27'): 0.8949335971099989,
 ('A01', 'PRODUCT12', '28'): 0.7686795693554124,
 ('A01', 'PRODUCT12', '29'): 0.7451409411627766,
 ('A01', 'PRODUCT12', '30'): 0.6920736043460097,
 ('A01', 'PRODUCT12', '31'): 0.7504773119401703,
 ('A01', 'PRODUCT12', '32'): 0.7913358588698438,
 ('A01', 'PRODUCT12', '33'): 0.8271002124328398,
 ('A01', 'PRODUCT12', '34'): 0.8317523896862515,
 ('A01', 'PRODUCT12', '35'): 0.9215256929356531,
 ('A01', 'PRODUCT12', '36'): 1.0111364155456923,
 ('A01', 'PRODUCT12', '37'): 0.8079106163431388,
 ('A01', 'PRODUCT12', '38'): 0.7312318287556886,
 ('A01', 'PRODUCT12', '39'): 0.7099727166107748,
 ('A01', 'PRODUCT12', '40'): 0.7347544092751995,
 ('A01', 'PRODUCT12', '41'): 0.7067837651116213,
 ('A01', 'PRODUCT12', '42'): 0.6685637664749277,
 ('A01', 'PRODUCT12', '43'): 0.6666822342839774,
 ('A01', 'PRODUCT12', '44'): 0.7282393288624309,
 ('A01', 'PRODUCT12', '45'): 0.821226986835886,
 ('A01', 'PRODUCT12', '46'): 1.2829035026259608,
 ('A01', 'PRODUCT12', '47'): 3.9700041325836,
 ('A01', 'PRODUCT12', '48'): 5.831259469418474,
 ('A01', 'PRODUCT12', '49'): 2.3772100764952984,
 ('A01', 'PRODUCT12', '50'): 1.4112016432108596,
 ('A01', 'PRODUCT12', '51'): 1.852846869392869,
 ('A01', 'PRODUCT12', '52'): 1.5905297819755198,
 ('A01', 'PRODUCT14', '01'): 0.8456394590768544,
 ('A01', 'PRODUCT14', '02'): 0.5834481987855308,
 ('A01', 'PRODUCT14', '03'): 0.6037886972395038,
 ('A01', 'PRODUCT14', '04'): 0.6936258987445517,
 ('A01', 'PRODUCT14', '05'): 0.6509145773572254,
 ('A01', 'PRODUCT14', '06'): 0.7305070223149425,
 ('A01', 'PRODUCT14', '07'): 0.9107029765674479,
 ('A01', 'PRODUCT14', '08'): 0.8826323436277616,
 ('A01', 'PRODUCT14', '09'): 0.6690384830309579,
 ('A01', 'PRODUCT14', '10'): 0.6139030659762321,
 ('A01', 'PRODUCT14', '11'): 0.6094139999254927,
 ('A01', 'PRODUCT14', '12'): 0.6663748463286518,
 ('A01', 'PRODUCT14', '13'): 0.6575271020377752,
 ('A01', 'PRODUCT14', '14'): 0.6477293894125098,
 ('A01', 'PRODUCT14', '15'): 0.6700629586856909,
 ('A01', 'PRODUCT14', '16'): 0.6858585105986664,
 ('A01', 'PRODUCT14', '17'): 0.6126364415303804,
 ('A01', 'PRODUCT14', '18'): 0.5861863428081809,
 ('A01', 'PRODUCT14', '19'): 0.6601348582498231,
 ('A01', 'PRODUCT14', '20'): 0.7682263532392059,
 ('A01', 'PRODUCT14', '21'): 1.1700070781954326,
 ('A01', 'PRODUCT14', '22'): 1.4795104869053386,
 ('A01', 'PRODUCT14', '23'): 0.9172596207577395,
 ('A01', 'PRODUCT14', '24'): 0.7831836977983088,
 ('A01', 'PRODUCT14', '25'): 1.0426368140669822,
 ('A01', 'PRODUCT14', '26'): 1.3616957866110344,
 ('A01', 'PRODUCT14', '27'): 1.8875684536005661,
 ('A01', 'PRODUCT14', '28'): 1.665424877994263,
 ('A01', 'PRODUCT14', '29'): 1.1425138769884142,
 ('A01', 'PRODUCT14', '30'): 1.0057370636665053,
 ('A01', 'PRODUCT14', '31'): 1.0451328092985137,
 ('A01', 'PRODUCT14', '32'): 0.9192340647468615,
 ('A01', 'PRODUCT14', '33'): 0.8707856796930299,
 ('A01', 'PRODUCT14', '34'): 1.0287970793130425,
 ('A01', 'PRODUCT14', '35'): 1.4117274522221808,
 ('A01', 'PRODUCT14', '36'): 1.7615393212383121,
 ('A01', 'PRODUCT14', '37'): 1.3256156167343442,
 ('A01', 'PRODUCT14', '38'): 0.9751518086652015,
 ('A01', 'PRODUCT14', '39'): 0.8212941921543792,
 ('A01', 'PRODUCT14', '40'): 0.7148977387028276,
 ('A01', 'PRODUCT14', '41'): 0.7677606824870544,
 ('A01', 'PRODUCT14', '42'): 0.7386096934023768,
 ('A01', 'PRODUCT14', '43'): 0.6123942927392617,
 ('A01', 'PRODUCT14', '44'): 0.6765823492158104,
 ('A01', 'PRODUCT14', '45'): 1.0973996945199866,
 ('A01', 'PRODUCT14', '46'): 1.4427783779756362,
 ('A01', 'PRODUCT14', '47'): 1.9320865775062401,
 ('A01', 'PRODUCT14', '48'): 2.602522072793652,
 ('A01', 'PRODUCT14', '49'): 1.8338673024624672,
 ('A01', 'PRODUCT14', '50'): 1.0597734977461535,
 ('A01', 'PRODUCT14', '51'): 1.0517080803188914,
 ('A01', 'PRODUCT14', '52'): 1.10645233394181,
 ('A01', 'PRODUCT15', '01'): 1.5764564104707075,
 ('A01', 'PRODUCT15', '02'): 0.9807115001732178,
 ('A01', 'PRODUCT15', '03'): 0.9330462996787722,
 ('A01', 'PRODUCT15', '04'): 0.8918299204276928,
 ('A01', 'PRODUCT15', '05'): 1.1473294142545372,
 ('A01', 'PRODUCT15', '06'): 1.0592188892228929,
 ('A01', 'PRODUCT15', '07'): 1.1601569608581894,
 ('A01', 'PRODUCT15', '08'): 0.874446141423836,
 ('A01', 'PRODUCT15', '09'): 1.009450812236045,
 ('A01', 'PRODUCT15', '10'): 0.9665521317910443,
 ('A01', 'PRODUCT15', '11'): 0.8255192150339493,
 ('A01', 'PRODUCT15', '12'): 0.9122278224039923,
 ('A01', 'PRODUCT15', '13'): 0.977837568966935,
 ('A01', 'PRODUCT15', '14'): 1.082560818288555,
 ('A01', 'PRODUCT15', '15'): 0.9509207498641893,
 ('A01', 'PRODUCT15', '16'): 0.9880715678966249,
 ('A01', 'PRODUCT15', '17'): 0.9456635586331842,
 ('A01', 'PRODUCT15', '18'): 0.9074613023545478,
 ('A01', 'PRODUCT15', '19'): 0.9962026903339126,
 ('A01', 'PRODUCT15', '20'): 0.8729741278791548,
 ('A01', 'PRODUCT15', '21'): 1.0219979753073771,
 ('A01', 'PRODUCT15', '22'): 1.0096610998852853,
 ('A01', 'PRODUCT15', '23'): 0.8225050920615065,
 ('A01', 'PRODUCT15', '24'): 1.0086797575221647,
 ('A01', 'PRODUCT15', '25'): 0.739371374728547,
 ('A01', 'PRODUCT15', '26'): 0.9303826561217297,
 ('A01', 'PRODUCT15', '27'): 1.2550667865486,
 ('A01', 'PRODUCT15', '28'): 0.8685580872451105,
 ('A01', 'PRODUCT15', '29'): 0.9159429042072357,
 ('A01', 'PRODUCT15', '30'): 0.9659913647264037,
 ('A01', 'PRODUCT15', '31'): 0.8277622832925116,
 ('A01', 'PRODUCT15', '32'): 1.0129556063900484,
 ('A01', 'PRODUCT15', '33'): 0.9221814378013619,
 ('A01', 'PRODUCT15', '34'): 0.9719495147882093,
 ('A01', 'PRODUCT15', '35'): 0.8152852161042595,
 ('A01', 'PRODUCT15', '36'): 1.034264754846389,
 ('A01', 'PRODUCT15', '37'): 0.8161964625843003,
 ('A01', 'PRODUCT15', '38'): 0.8028081489160076,
 ('A01', 'PRODUCT15', '39'): 0.6990662419575084,
 ('A01', 'PRODUCT15', '40'): 0.9651502141294429,
 ('A01', 'PRODUCT15', '41'): 0.8265706532801503,
 ('A01', 'PRODUCT15', '42'): 0.9057790011606262,
 ('A01', 'PRODUCT15', '43'): 0.9783282401484955,
 ('A01', 'PRODUCT15', '44'): 0.6658407933775567,
 ('A01', 'PRODUCT15', '45'): 0.9582107217045163,
 ('A01', 'PRODUCT15', '46'): 0.9083725488345885,
 ('A01', 'PRODUCT15', '47'): 0.990384732038267,
 ('A01', 'PRODUCT15', '48'): 1.2297621727566959,
 ('A01', 'PRODUCT15', '49'): 1.5695169180457806,
 ('A01', 'PRODUCT15', '50'): 1.1702507680217191,
 ('A01', 'PRODUCT15', '51'): 1.6413651982028494,
 ('A01', 'PRODUCT15', '52'): 1.691203371072777,
 ('A01', 'PRODUCT16', '01'): 0.819637316417293,
 ('A01', 'PRODUCT16', '02'): 0.58227952837344,
 ('A01', 'PRODUCT16', '03'): 0.6066606908915397,
 ('A01', 'PRODUCT16', '04'): 0.6508814268312304,
 ('A01', 'PRODUCT16', '05'): 0.8110322002344343,
 ('A01', 'PRODUCT16', '06'): 0.7988416189753845,
 ('A01', 'PRODUCT16', '07'): 0.8954101450274656,
 ('A01', 'PRODUCT16', '08'): 0.8466478199912663,
 ('A01', 'PRODUCT16', '09'): 0.8246569675239606,
 ('A01', 'PRODUCT16', '10'): 0.681716426486474,
 ('A01', 'PRODUCT16', '11'): 0.6958192557861592,
 ('A01', 'PRODUCT16', '12'): 0.6018800707899515,
 ('A01', 'PRODUCT16', '13'): 0.6795651474407594,
 ('A01', 'PRODUCT16', '14'): 0.713268519156956,
 ('A01', 'PRODUCT16', '15'): 0.7954951849042727,
 ('A01', 'PRODUCT16', '16'): 0.7412351467512469,
 ('A01', 'PRODUCT16', '17'): 0.7395619297156911,
 ('A01', 'PRODUCT16', '18'): 0.9659242915258913,
 ('A01', 'PRODUCT16', '19'): 0.8784389436668277,
 ('A01', 'PRODUCT16', '20'): 0.8915856489461951,
 ('A01', 'PRODUCT16', '21'): 1.056995104461146,
 ('A01', 'PRODUCT16', '22'): 1.0431313061665404,
 ('A01', 'PRODUCT16', '23'): 0.9649681675055737,
 ('A01', 'PRODUCT16', '24'): 1.0139695235468524,
 ('A01', 'PRODUCT16', '25'): 0.8002758050058608,
 ('A01', 'PRODUCT16', '26'): 0.809119952193799,
 ('A01', 'PRODUCT16', '27'): 1.1191431657817923,
 ('A01', 'PRODUCT16', '28'): 0.9078397572915948,
 ('A01', 'PRODUCT16', '29'): 0.8559700291893632,
 ('A01', 'PRODUCT16', '30'): 0.7895194097772874,
 ('A01', 'PRODUCT16', '31'): 0.8894343699004805,
 ('A01', 'PRODUCT16', '32'): 0.9078397572915948,
 ('A01', 'PRODUCT16', '33'): 0.9389137879519179,
 ('A01', 'PRODUCT16', '34'): 0.7452986738375968,
 ('A01', 'PRODUCT16', '35'): 0.9511043692109679,
 ('A01', 'PRODUCT16', '36'): 1.0524535153646373,
 ('A01', 'PRODUCT16', '37'): 0.8741363855753982,
 ('A01', 'PRODUCT16', '38'): 0.8992346411087361,
 ('A01', 'PRODUCT16', '39'): 0.7995587119906227,
 ('A01', 'PRODUCT16', '40'): 1.0240088257601876,
 ('A01', 'PRODUCT16', '41'): 0.9422602220230297,
 ('A01', 'PRODUCT16', '42'): 0.8829805327633363,
 ('A01', 'PRODUCT16', '43'): 0.7876071617366524,
 ('A01', 'PRODUCT16', '44'): 0.9537337102668414,
 ('A01', 'PRODUCT16', '45'): 0.9458456870992209,
 ('A01', 'PRODUCT16', '46'): 1.2594543657634052,

In [51]:
seasonMap["A00","PRODUCT34","01"]

2.0868140868140865

In [52]:
("A00","PRODUCT34","01")in seasonMap

True

In [53]:
groupKey2 = ["REGIONID","PRODUCT"]

In [54]:
groupData2=sortedData.groupby(groupKey2)

In [55]:
len(groupData2)

794

In [56]:
len(sortedData[["REGIONID","PRODUCT"]].drop_duplicates())    ##drop_duplicates 중복 제거

794

In [57]:
oneGroup = groupData2.get_group(list(groupData2.groups)[0])

In [58]:
len(oneGroup)

156

In [59]:
def mafunction(oneGroup,in_window):
    eachData = oneGroup.reset_index(drop=True)

    eachData["MA"] = eachData.NEW_QTY.rolling(window=in_window, center =True, min_periods=1).mean()

    return eachData

In [60]:
WINDOW = 5

In [61]:
groupData2=sortedData.groupby(groupKey2).apply(mafunction,(WINDOW))

In [62]:
emptyColumns= ["REGIONID","PRODUCT","ITME","YEARWEEK","QTY"]

In [63]:
emptydf=pd.DataFrame(columns=emptyColumns)

In [64]:
emptydf

Empty DataFrame
Columns: [REGIONID, PRODUCT, ITME, YEARWEEK, QTY]
Index: []

In [65]:
REGIONID ="A00"
PRODUCT ="PRODUCT34"
ITEM="ITEM01"
STARTWEEK ="201925"

In [66]:
PAST_WINDOW = 4

In [67]:
from fintechlab import CommonFunction as cf

In [68]:
for i in range(0, PAST_WINDOW):
    emptydf = emptydf.append(pd.DataFrame([[REGIONID,PRODUCT,ITEM,cf.preWeek(STARTWEEK,i),100+(i*10)]],
                               columns = emptyColumns),
                  ignore_index=True)

In [69]:
emptydf

  REGIONID    PRODUCT    ITME YEARWEEK  QTY
0      A00  PRODUCT34  ITEM01   201925  100
1      A00  PRODUCT34  ITEM01   201924  110
2      A00  PRODUCT34  ITEM01   201923  120
3      A00  PRODUCT34  ITEM01   201922  130

In [70]:
cf.preWeek("201925",1)

'201924'

In [71]:
print((seasonMap["A00", "PRODUCT34", "25"]+
seasonMap["A00", "PRODUCT34", "24"]+
seasonMap["A00", "PRODUCT34", "23"]+
seasonMap["A00", "PRODUCT34", "22"])/4)

0.40897046779399715

In [72]:
stdQty=emptydf.QTY.mean()
stdQty

115.0

In [73]:
weekList=emptydf.YEARWEEK.str[4:6]
seasonList =[]
for i in weekList:
    seasonList.append(seasonMap[REGIONID,PRODUCT,i])
    stdSeasonality = sum(seasonList)/ len(weekList)

In [74]:
stdSeasonality

0.40897046779399715

In [75]:
sum(seasonList)

1.6358818711759886

In [76]:
len(weekList)

4

In [77]:
FCST_WINDOW =5

In [78]:
STARTWEEK

'201925'

In [79]:
for i in range (0,FCST_WINDOW):
    emptydf = emptydf.append(pd.DataFrame([[REGIONID,PRODUCT,ITEM,cf.postWeek(STARTWEEK,i+1),0]],columns=emptyColumns),ignore_index=True)

In [80]:
emptydf["FCST"]=0
emptydf["AVG_QTY"]=stdQty
emptydf["AVG_SEASON"]=stdSeasonality

In [81]:
emptydf

  REGIONID    PRODUCT    ITME YEARWEEK  QTY  FCST  AVG_QTY  AVG_SEASON
0      A00  PRODUCT34  ITEM01   201925  100     0    115.0     0.40897
1      A00  PRODUCT34  ITEM01   201924  110     0    115.0     0.40897
2      A00  PRODUCT34  ITEM01   201923  120     0    115.0     0.40897
3      A00  PRODUCT34  ITEM01   201922  130     0    115.0     0.40897
4      A00  PRODUCT34  ITEM01   201926    0     0    115.0     0.40897
5      A00  PRODUCT34  ITEM01   201927    0     0    115.0     0.40897
6      A00  PRODUCT34  ITEM01   201928    0     0    115.0     0.40897
7      A00  PRODUCT34  ITEM01   201929    0     0    115.0     0.40897
8      A00  PRODUCT34  ITEM01   201930    0     0    115.0     0.40897

In [82]:
def seasonmapping(yearweek):
    week=yearweek[4:6]
    seasonality=seasonMap[REGIONID,PRODUCT,week]
    return seasonality

In [83]:
emptydf ["SEASONALITY"] = emptydf["YEARWEEK"].apply(seasonmapping)

In [84]:
emptydf["FCST"] = emptydf.AVG_QTY/emptydf.AVG_SEASON*emptydf.SEASONALITY
### 예측값 최근 한달간 판매량/최근 한달간 계절성 지수 * 예측주차의 계절성 지수

In [85]:
emptydf

,REGIONID,PRODUCT,ITME,YEARWEEK,QTY,FCST,AVG_QTY,AVG_SEASON,SEASONALITY
0,A00,PRODUCT34,ITEM01,201925,100,79.601838,115.0,0.40897,0.283085
1,A00,PRODUCT34,ITEM01,201924,110,112.006126,115.0,0.40897,0.398323
2,A00,PRODUCT34,ITEM01,201923,120,123.277182,115.0,0.40897,0.438406
3,A00,PRODUCT34,ITEM01,201922,130,145.114855,115.0,0.40897,0.516067
4,A00,PRODUCT34,ITEM01,201926,0,70.444104,115.0,0.40897,0.250518
5,A00,PRODUCT34,ITEM01,201927,0,86.646248,115.0,0.40897,0.308137
6,A00,PRODUCT34,ITEM01,201928,0,138.774885,115.0,0.40897,0.493520
7,A00,PRODUCT34,ITEM01,201929,0,505.084227,115.0,0.40897,1.796213
8,A00,PRODUCT34,ITEM01,201930,0,395.895865,115.0,0.40897,1.407911

In [86]:
qty =[10,100,200]
predict =[20,150,200]
pd.DataFrame(zip(qty,predict))

     0    1
0   10   20
1  100  150
2  200  200