In [2]:
import pandas as pd
import requests
from pandas.io.json import json_normalize


##데이터 접속 주소 입력
url='http://kosis.kr/openapi/statisticsData.do?method=getList&apiKey=M2E3NzliMTYyNGIyYzU3MTcwMzNmNjZhMjlmYWU4YWM=&format=json&jsonVD=Y&userStatsId=dlatjsdud128/408/DT_40803_N0005/2/1/20190418173155&prdSe=M&newEstPrdCnt=1'

#정상 여부 확인(200정상)
response=requests.get(url)
response

#JSON데이터 획득
json=response.json()

#PandasDataframe변환
df=json_normalize(json)
df.head()

,C1,C1_NM,C1_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,C2,C2_NM,C2_NM_ENG,C2_OBJ_NM,C2_OBJ_NM_ENG,...,ITM_ID,ITM_NM,ITM_NM_ENG,ORG_ID,PRD_DE,PRD_SE,TBL_ID,TBL_NM,UNIT_NM,UNIT_NM_ENG
0,01,아파트,Apartments,주택유형,Region,a0,전국,The Whole Country,지역,Region,...,sales,매매가격,Sales Price Index,408,201903,M,DT_40803_N0005,연령별 매매가격지수,2017.11 ＝ 100.0,2017.11 ＝ 100.0
1,01,아파트,Apartments,주택유형,Region,a0,전국,The Whole Country,지역,Region,...,sales,매매가격,Sales Price Index,408,201903,M,DT_40803_N0005,연령별 매매가격지수,2017.11 ＝ 100.0,2017.11 ＝ 100.0
2,01,아파트,Apartments,주택유형,Region,a0,전국,The Whole Country,지역,Region,...,sales,매매가격,Sales Price Index,408,201903,M,DT_40803_N0005,연령별 매매가격지수,2017.11 ＝ 100.0,2017.11 ＝ 100.0
3,01,아파트,Apartments,주택유형,Region,a0,전국,The Whole Country,지역,Region,...,sales,매매가격,Sales Price Index,408,201903,M,DT_40803_N0005,연령별 매매가격지수,2017.11 ＝ 100.0,2017.11 ＝ 100.0
4,01,아파트,Apartments,주택유형,Region,a0,전국,The Whole Country,지역,Region,...,sales,매매가격,Sales Price Index,408,201903,M,DT_40803_N0005,연령별 매매가격지수,2017.11 ＝ 100.0,2017.11 ＝ 100.0

In [3]:
df.to_csv("./98_연령별 매매가격지수.csv",encoding="ms949")## 한글 안떠서 encoding="ms949"