In [1]:
import pandas as pd
import numpy as np
import math
#모델 라이브러리 선언
from sklearn import datasets, tree
#모델 정확도 라이브러리 선언
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

C:\Users\SMART-14\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [2]:
###  kopo_decision_tree_all_new.csv 파일을 열고 판매량을 예측하는 모델을 생성하세요    ###

In [3]:
kopoData = pd.read_csv("./dataset/kopo_decision_tree_all_new.csv")

In [171]:
kopoDataa

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,PRO_YN,H_YN
0,A01,PG01,P01,ITEM001,201538,2015,38,1,N,4,N,0.000000,0,0
1,A01,PG01,P01,ITEM001,201548,2015,48,1,Y,0,N,0.000000,0,1
2,A01,PG01,P01,ITEM001,201549,2015,49,2,Y,0,N,0.000000,0,1
3,A01,PG01,P01,ITEM002,201526,2015,26,1,Y,1,N,0.000000,0,1
4,A01,PG01,P01,ITEM002,201532,2015,32,1,N,4,N,0.000000,0,0
5,A01,PG01,P01,ITEM003,201553,2015,53,2,Y,1,N,0.000000,0,1
6,A01,PG01,P01,ITEM004,201501,2015,1,63,Y,1,Y,0.345902,1,1
7,A01,PG01,P01,ITEM004,201502,2015,2,33,N,4,Y,0.345902,1,0
8,A01,PG01,P01,ITEM004,201503,2015,3,7,N,4,N,0.000000,0,0
9,A01,PG01,P01,ITEM004,201504,2015,4,6,Y,2,N,0.000000,0,1
10,A01,PG01,P01,ITEM004,201505,2015,5,33,N,4,N,0.000000,0,0
11,A01,PG01,P01,ITEM004,201506,2015,6,39,N,4,N,0.000000,0,0
12,A01,PG01,P01,ITEM004,201507,2015,7,21,N,4,N,0.000000,0,0
13,A01,PG01,P01,ITEM005,201501,2015,1,572,Y,1,Y,0.446687,1,1
14,A01,PG01,P01,ITEM005,201502,2015,2,405,N,4,Y,0.446687,1,0
15,A01,PG01,P01,ITEM005,201503,2015,3,37,N,4,N,0.000000,0,0
16,A01,PG01,P01,ITEM005,201504,2015,4,43,Y,2,N,0.000000,0,1
17,A01,PG01,P01,ITEM005,201505,2015,5,292,N,4,N,0.000000,0,0
18,A01,PG01,P01,ITEM005,201506,2015,6,288,N,4,N,0.000000,0,0
19,A01,PG01,P01,ITEM005,201507,2015,7,124,N,4,N,0.000000,0,0
20,A01,PG01,P01,ITEM005,201508,2015,8,19,Y,1,N,0.000000,0,1
21,A01,PG01,P01,ITEM006,201501,2015,1,82,Y,1,Y,0.345902,1,1
22,A01,PG01,P01,ITEM006,201502,2015,2,47,N,4,Y,0.345902,1,0
23,A01,PG01,P01,ITEM006,201503,2015,3,3,N,4,N,0.000000,0,0
24,A01,PG01,P01,ITEM006,201504,2015,4,4,Y,2,N,0.000000,0,1
25,A01,PG01,P01,ITEM006,201505,2015,5,45,N,4,N,0.000000,0,0
26,A01,PG01,P01,ITEM006,201506,2015,6,35,N,4,N,0.000000,0,0
27,A01,PG01,P01,ITEM006,201507,2015,7,15,N,4,N,0.000000,0,0
28,A01,PG01,P01,ITEM006,201508,2015,8,16,Y,1,N,0.000000,0,1
29,A01,PG01,P01,ITEM007,201501,2015,1,64,Y,1,Y,0.230354,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32385,A01,PG05,P16,ITEM490,201616,2016,16,11,N,4,N,0.000000,0,0
32386,A01,PG05,P16,ITEM490,201617,2016,17,5,N,4,Y,0.211294,1,0
32387,A01,PG05,P16,ITEM490,201618,2016,18,7,N,4,Y,0.211294,1,0
32388,A01,PG05,P16,ITEM490,201619,2016,19,10,N,4,Y,0.211294,1,0
32389,A01,PG05,P16,ITEM490,201620,2016,20,8,Y,1,Y,0.211294,1,1
32390,A01,PG05,P16,ITEM490,201621,2016,21,12,Y,1,Y,0.211294,1,1
32391,A01,PG05,P16,ITEM490,201622,2016,22,22,Y,1,Y,0.211294,1,1
32392,A01,PG05,P16,ITEM490,201623,2016,23,7,N,4,Y,0.211294,1,0
32393,A01,PG05,P16,ITEM490,201624,2016,24,3,N,4,N,0.000000,0,0
32394,A01,PG05,P16,ITEM490,201625,2016,25,3,Y,1,N,0.000000,0,1
32395,A01,PG05,P16,ITEM490,201626,2016,26,3,Y,1,N,0.000000,0,1
32396,A01,PG05,P16,ITEM490,201627,2016,27,4,Y,1,N,0.000000,0,1
32397,A01,PG05,P16,ITEM490,201628,2016,28,1,Y,1,N,0.000000,0,1
32398,A01,PG05,P16,ITEM490,201629,2016,29,3,Y,1,N,0.000000,0,1
32399,A01,PG05,P16,ITEM490,201630,2016,30,3,N,4,N,0.000000,0,0
32400,A01,PG05,P16,ITEM490,201631,2016,31,5,N,4,N,0.000000,0,0
32401,A01,PG05,P16,ITEM490,201632,2016,32,1,N,4,N,0.000000,0,0
32402,A01,PG05,P16,ITEM490,201633,2016,33,3,N,4,N,0.000000,0,0
32403,A01,PG05,P16,ITEM490,201634,2016,34,4,Y,1,Y,0.211294,1,1
32404,A01,PG05,P16,ITEM490,201635,2016,35,7,Y,1,Y,0.211294,1,1
32405,A01,PG05,P16,ITEM490,201636,2016,36,11,Y,1,Y,0.211294,1,1
32406,A01,PG05,P16,ITEM490,201637,2016,37,3,N,4,Y,0.211294,1,0
32407,A01,PG05,P16,ITEM490,201638,2016,38,7,N,4,N,0.000000,0,0
32408,A01,PG05,P16,ITEM490,201639,2016,39,3,N,4,N,0.000000,0,0
32409,A01,PG05,P16,ITEM490,201640,2016,40,1,N,4,N,0.000000,0,0
32410,A01,PG05,P16,ITEM491,201503,2015,3,1,N,4,N,0.000000,0,0
32411,A01,PG05,P16,ITEM491,201504,2015,4,1,Y,2,N,0.000000,0,1
32412,A01,PG05,P16,ITEM491,201505,2015,5,2,N,4,N,0.000000,0,0
32413,A01,PG05,P16,ITEM491,201506,2015,6,1,N,4,N,0.000000,0,0
32414,A01,PG05,P16,ITEM491,201508,2015,8,1,Y,1,N,0.000000,0,1

In [12]:
kopoData.dtypes
kopoData["PRO_YN"] = np.where(kopoData.PROMOTION=="Y",1,0)
kopoData["H_YN"] = np.where(kopoData.HOLIDAY=="Y",1,0)
kopoData.head(2)

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,PRO_YN,H_YN
0,A01,PG01,P01,ITEM001,201538,2015,38,1,N,4,N,0.0,0,0
1,A01,PG01,P01,ITEM001,201548,2015,48,1,Y,0,N,0.0,0,1

In [126]:
groupKey = ["REGIONID","PRODUCTGROUP","PRODUCT","ITEM"]

In [130]:
kopoDataCount = kopoData.groupby(groupKey)["YEARWEEK"].\
                agg(["size"]).reset_index()

In [132]:
kopoDataCount.rename(columns={"size":"KNOB"},inplace=True)

In [136]:
mergedData = pd.merge(kopoData,kopoDataCount, on = groupKey)

In [137]:
mergedData.KNOB.max()

146

In [139]:
refindData = mergedData[mergedData.KNOB == mergedData.KNOB.max() ]

In [144]:
len(refindData["ITEM"].drop_duplicates())

52

In [7]:
#상관관계 확인
corrDf=kopoData.corr()
corrDf

,YEARWEEK,YEAR,WEEK,QTY,HCLUS,PRO_PERCENT,PRO_YN,H_YN
YEARWEEK,1.000000,0.984528,0.005567,-0.021432,0.016040,0.161164,0.118040,0.001566
YEAR,0.984528,1.000000,-0.169746,-0.039309,0.068345,0.122548,0.097886,-0.041092
WEEK,0.005567,-0.169746,1.000000,0.103788,-0.299818,0.207041,0.105250,0.243307
QTY,-0.021432,-0.039309,0.103788,1.000000,-0.184016,0.237682,0.095984,0.157853
HCLUS,0.016040,0.068345,-0.299818,-0.184016,1.000000,-0.289396,-0.143294,-0.977417
PRO_PERCENT,0.161164,0.122548,0.207041,0.237682,-0.289396,1.000000,0.812344,0.254015
PRO_YN,0.118040,0.097886,0.105250,0.095984,-0.143294,0.812344,1.000000,0.136497
H_YN,0.001566,-0.041092,0.243307,0.157853,-0.977417,0.254015,0.136497,1.000000

In [146]:
groupKey = ["REGIONID","PRODUCTGROUP","PRODUCT","ITEM"]
groupData=refindData.groupby(groupKey)
len(groupData)

52

In [160]:
def mlfunction(onegroup):

    #onegroup = groupData.get_group(list(groupData.groups)[8])

    eachgroup = onegroup.reset_index(drop=True)
    eachgroup.head(2)

    #     1. 상관관계를 산출
    #     2. 데이터를 분리
    #     3. 모델 선언 및 학습
    #     4. 예측
    ##상관관계 산출 후 feature와 lebel 정의 corrdf = eachgroup.corr()

    features=list(corrdf[abs(corrdf.QTY>0.5)&(corrdf.QTY != 1)].index)

    #len(features) == 0 

    label=["QTY"]

    ##데이터 분리

    stdindex=round(len(eachgroup)*0.8)

    stdYearweek=eachgroup.loc[stdindex,["YEARWEEK"]].values[0] 

    stdYearweek = 201700

    trainingData_features = eachgroup[eachgroup.YEARWEEK <= stdYearweek][features]
    trainingData_label = eachgroup[eachgroup.YEARWEEK <= stdYearweek][label]
    testData_features = eachgroup[eachgroup.YEARWEEK > stdYearweek][features]
    testData_label = eachgroup[eachgroup.YEARWEEK > stdYearweek][label]
    testData_label2 = eachgroup[eachgroup.YEARWEEK > stdYearweek]

    ##모델 선언 및 학습

    model_method = tree.DecisionTreeRegressor(random_state=1) 
    model=model_method.fit(trainingData_features,trainingData_label)

    ##예측

    testData_label2["PREDICT"] = model.predict(testData_features)

    return testData_label2

In [166]:
finalData = refindData.groupby(groupKey).apply(mlfunction)

In [168]:
finalData.reset_index(drop=True)

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,PRO_YN,H_YN,KNOB,PREDICT
0,A01,PG02,P03,ITEM043,201701,2017,1,470,Y,1,Y,0.240964,1,1,146,386.000000
1,A01,PG02,P03,ITEM043,201702,2017,2,293,N,4,Y,0.240964,1,0,146,386.000000
2,A01,PG02,P03,ITEM043,201703,2017,3,285,Y,2,Y,0.201205,1,1,146,244.175000
3,A01,PG02,P03,ITEM043,201704,2017,4,304,N,4,Y,0.201205,1,0,146,244.175000
4,A01,PG02,P03,ITEM043,201705,2017,5,366,N,4,Y,0.320482,1,0,146,455.000000
5,A01,PG02,P03,ITEM043,201706,2017,6,481,N,4,Y,0.320482,1,0,146,455.000000
6,A01,PG02,P03,ITEM043,201707,2017,7,442,N,4,Y,0.320482,1,0,146,455.000000
7,A01,PG02,P03,ITEM043,201708,2017,8,485,Y,1,Y,0.320482,1,1,146,455.000000
8,A01,PG02,P03,ITEM043,201709,2017,9,331,N,4,Y,0.320482,1,0,146,455.000000
9,A01,PG02,P03,ITEM043,201710,2017,10,189,N,4,Y,0.121687,1,0,146,73.500000
10,A01,PG02,P03,ITEM043,201711,2017,11,219,N,4,Y,0.201205,1,0,146,244.175000
11,A01,PG02,P03,ITEM043,201712,2017,12,322,N,4,Y,0.201205,1,0,146,244.175000
12,A01,PG02,P03,ITEM043,201713,2017,13,366,N,4,Y,0.201205,1,0,146,244.175000
13,A01,PG02,P03,ITEM043,201714,2017,14,500,N,4,Y,0.201205,1,0,146,244.175000
14,A01,PG02,P03,ITEM043,201715,2017,15,323,N,4,Y,0.201205,1,0,146,244.175000
15,A01,PG02,P03,ITEM043,201716,2017,16,170,N,4,Y,0.121687,1,0,146,73.500000
16,A01,PG02,P03,ITEM043,201717,2017,17,203,N,4,Y,0.121687,1,0,146,73.500000
17,A01,PG02,P03,ITEM043,201718,2017,18,201,N,4,Y,0.121687,1,0,146,73.500000
18,A01,PG02,P03,ITEM043,201719,2017,19,151,N,4,N,0.000000,0,0,146,103.093750
19,A01,PG02,P03,ITEM043,201720,2017,20,273,Y,1,Y,0.201205,1,1,146,244.175000
20,A01,PG02,P03,ITEM043,201721,2017,21,590,Y,1,Y,0.201205,1,1,146,244.175000
21,A01,PG02,P03,ITEM043,201722,2017,22,595,Y,1,Y,0.201205,1,1,146,244.175000
22,A01,PG02,P03,ITEM043,201723,2017,23,399,N,4,Y,0.201205,1,0,146,244.175000
23,A01,PG02,P03,ITEM043,201724,2017,24,241,N,4,Y,0.280723,1,0,146,643.000000
24,A01,PG02,P03,ITEM043,201725,2017,25,447,Y,1,Y,0.280723,1,1,146,643.000000
25,A01,PG02,P03,ITEM043,201726,2017,26,447,Y,1,Y,0.280723,1,1,146,643.000000
26,A01,PG02,P03,ITEM043,201727,2017,27,548,Y,1,Y,0.280723,1,1,146,643.000000
27,A01,PG02,P03,ITEM043,201728,2017,28,457,Y,1,Y,0.280723,1,1,146,643.000000
28,A01,PG02,P03,ITEM043,201729,2017,29,423,Y,1,Y,0.280723,1,1,146,643.000000
29,A01,PG02,P03,ITEM043,201730,2017,30,408,N,4,Y,0.201205,1,0,146,244.175000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,A01,PG05,P15,ITEM376,201712,2017,12,230,N,4,N,0.000000,0,0,146,56.840000
2103,A01,PG05,P15,ITEM376,201713,2017,13,183,N,4,N,0.000000,0,0,146,56.840000
2104,A01,PG05,P15,ITEM376,201714,2017,14,220,N,4,Y,0.245307,1,0,146,279.266667
2105,A01,PG05,P15,ITEM376,201715,2017,15,195,N,4,Y,0.245307,1,0,146,279.266667
2106,A01,PG05,P15,ITEM376,201716,2017,16,185,N,4,Y,0.245307,1,0,146,279.266667
2107,A01,PG05,P15,ITEM376,201717,2017,17,105,N,4,Y,0.245307,1,0,146,279.266667
2108,A01,PG05,P15,ITEM376,201718,2017,18,47,N,4,Y,0.245307,1,0,146,279.266667
2109,A01,PG05,P15,ITEM376,201719,2017,19,173,N,4,Y,0.245307,1,0,146,279.266667
2110,A01,PG05,P15,ITEM376,201720,2017,20,221,Y,1,Y,0.245307,1,1,146,279.266667
2111,A01,PG05,P15,ITEM376,201721,2017,21,293,Y,1,Y,0.245307,1,1,146,279.266667
2112,A01,PG05,P15,ITEM376,201722,2017,22,302,Y,1,Y,0.245307,1,1,146,279.266667
2113,A01,PG05,P15,ITEM376,201723,2017,23,120,N,4,Y,0.245307,1,0,146,279.266667
2114,A01,PG05,P15,ITEM376,201724,2017,24,159,N,4,Y,0.271214,1,0,146,242.100000
2115,A01,PG05,P15,ITEM376,201725,2017,25,223,Y,1,Y,0.271214,1,1,146,242.100000
2116,A01,PG05,P15,ITEM376,201726,2017,26,203,Y,1,Y,0.271214,1,1,146,242.100000
2117,A01,PG05,P15,ITEM376,201727,2017,27,219,Y,1,Y,0.271214,1,1,146,242.100000
2118,A01,PG05,P15,ITEM376,201728,2017,28,236,Y,1,Y,0.271214,1,1,146,242.100000
2119,A01,PG05,P15,ITEM376,201729,2017,29,288,Y,1,Y,0.271214,1,1,146,242.100000
2120,A01,PG05,P15,ITEM376,201730,2017,30,286,N,4,Y,0.271214,1,0,146,242.100000
2121,A01,PG05,P15,ITEM376,201731,2017,31,257,N,4,Y,0.245307,1,0,146,279.266667
2122,A01,PG05,P15,ITEM376,201732,2017,32,172,N,4,Y,0.245307,1,0,146,279.266667
2123,A01,PG05,P15,ITEM376,201733,2017,33,242,N,4,Y,0.271214,1,0,146,242.100000
2124,A01,PG05,P15,ITEM376,201734,2017,34,257,Y,1,Y,0.271214,1,1,146,242.100000
2125,A01,PG05,P15,ITEM376,201735,2017,35,278,Y,1,Y,0.271214,1,1,146,242.100000
2126,A01,PG05,P15,ITEM376,201736,2017,36,241,Y,1,Y,0.271214,1,1,146,242.100000
2127,A01,PG05,P15,ITEM376,201737,2017,37,226,N,4,Y,0.271214,1,0,146,242.100000
2128,A01,PG05,P15,ITEM376,201738,2017,38,218,N,4,Y,0.271214,1,0,146,242.100000
2129,A01,PG05,P15,ITEM376,201739,2017,39,151,N,4,Y,0.245307,1,0,146,279.266667
2130,A01,PG05,P15,ITEM376,201740,2017,40,220,N,4,Y,0.245307,1,0,146,279.266667
2131,A01,PG05,P15,ITEM376,201741,2017,41,226,Y,2,Y,0.245307,1,1,146,279.266667

In [122]:
def mlFcst(onegroup): 
    
#     onegroup = groupData.get_group(list(groupData.groups)[index])

#         onegroup = groupData.get_group(list(groupData.groups)[7]) 
        eachgroup = onegroup.reset_index()

    #     1. 상관관계를 산출
    #     2. 데이터를 분리
    #     3. 모델 선언 및 학습
    #     4. 예측
        ##상관관계 산출 후 feature와 lebel 정의 corrdf = eachgroup.corr()

        features=list(corrdf[abs(corrdf.QTY>0.5)&(corrdf.QTY != 1)].index)
        

        label=["QTY"]

        ##데이터 분리

        stdindex=round(len(eachgroup)*0.8)

        stdYearweek=eachgroup.loc[stdindex,["YEARWEEK"]].values[0] 

        trainingData_features = eachgroup[eachgroup.YEARWEEK <= stdYearweek][features]
        trainingData_label = eachgroup[eachgroup.YEARWEEK <= stdYearweek][label]
        testData_features = eachgroup[eachgroup.YEARWEEK > stdYearweek][features]
        testData_label = eachgroup[eachgroup.YEARWEEK > stdYearweek][label]
        testData_label2 = eachgroup[eachgroup.YEARWEEK > stdYearweek]

        ##모델 선언 및 학습

        model_method = tree.DecisionTreeRegressor(random_state=1) 
        model=model_method.fit(trainingData_features,trainingData_label)

        ##예측

        testData_label2["PREDICT"] = model.predict(testData_features)

        return testData_label2

In [189]:
refindData.head(5)

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,PRO_YN,H_YN,KNOB
2352,A01,PG02,P03,ITEM043,201501,2015,1,87,Y,1,Y,0.197590,1,1,146
2353,A01,PG02,P03,ITEM043,201502,2015,2,60,N,4,Y,0.197590,1,0,146
2354,A01,PG02,P03,ITEM043,201503,2015,3,51,N,4,N,0.000000,0,0,146
2355,A01,PG02,P03,ITEM043,201504,2015,4,37,Y,2,N,0.000000,0,1,146
2356,A01,PG02,P03,ITEM043,201505,2015,5,136,N,4,Y,0.201205,1,0,146

In [190]:
from sklearn.preprocessing import LabelEncoder

le_pro = LabelEncoder()
le_holy =LabelEncoder()

refindData['HOLY_ENCO']= le_pro.fit_transform(refindData.PROMOTION)

C:\Users\SMART-14\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [191]:
refindData.head(5)

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT,PRO_YN,H_YN,KNOB,HOLY_ENCO
2352,A01,PG02,P03,ITEM043,201501,2015,1,87,Y,1,Y,0.197590,1,1,146,1
2353,A01,PG02,P03,ITEM043,201502,2015,2,60,N,4,Y,0.197590,1,0,146,1
2354,A01,PG02,P03,ITEM043,201503,2015,3,51,N,4,N,0.000000,0,0,146,0
2355,A01,PG02,P03,ITEM043,201504,2015,4,37,Y,2,N,0.000000,0,1,146,0
2356,A01,PG02,P03,ITEM043,201505,2015,5,136,N,4,Y,0.201205,1,0,146,1